import type { Metadata } from "next";

import localFont from "next/font/local";
import "@/styles/globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import CustomCursor from "@/components/ui/CustomCursor";

import { ReactLenis } from "lenis/react";

const modernist = localFont({
  src: "../fonts/Sk-Modernist-Regular.otf",
  variable: "--font-modernist",
});

const poppins = localFont({
  src: "../fonts/Poppins-Regular.ttf",
  variable: "--font-poppins",
});

const poppinsLight = localFont({
  src: "../fonts/Poppins-Light.ttf",
  variable: "--font-poppins-light",
});

const instrumentLight = localFont({
  src: "../fonts/InstrumentSerif.ttf",
  variable: "--font-instrument-light",
});

export const metadata: Metadata = {
  title: "Rohan Baburaj - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactLenis root>
        <body
          className={`${modernist.variable} ${poppinsLight.variable} ${poppins.variable} ${instrumentLight.variable} antialiased`}
        >
          <Header />
          <CustomCursor />
          {children}
          <Footer />
        </body>
      </ReactLenis>
    </html>
  );
}
