import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "@/styles/globals.css";
import Sidebar from "@/components/layout/SideBar";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

import { ReactLenis } from "@/utils/lenis";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const modernist = localFont({
  src: "../fonts/Sk-Modernist-Regular.otf",
  variable: "--font-modernist",
});

const poppins = localFont({
  src: "../fonts/Poppins-Regular.ttf",
  variable: "--font-poppins",
});

const poppinsLight = localFont({
  src: "../fonts/Poppins-Light.ttf",
  variable: "--font-poppins-light",
});

const instrumentLight = localFont({
  src: "../fonts/InstrumentSerif.ttf",
  variable: "--font-instrument-light",
});

export const metadata: Metadata = {
  title: "Rohan Baburaj - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactLenis root>
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${modernist.variable} ${poppinsLight.variable} ${poppins.variable} ${instrumentLight.variable} antialiased`}
        >
          <Header />
          {/* <Sidebar /> */}
          {children}
          <Footer />
        </body>
      </ReactLenis>
    </html>
  );
}
